### PR TITLE
Facilitate integration of the module as shared library

### PR DESCRIPTION
**Pull request by jcfr**
This commit will allow to create shared library depending on
the external module.

Co-authored-by: Matt McCormick (matt.mccormick@kitware.com)
Co-authored-by: Jean-Christophe Fillion-Robin (jchris.fillionr@kitware.com)

### CODE REVIEW

**Comment by jcfr** [comment]
@sumedhasingla I forced pushed master to avoid all the "incorrect" merges .. please consider this new PR.

**Comment by jcfr** [comment]
@thewtex Should Pr be done on InsightSoftwareConsortium/ITKMinimalPathExtraction instead of KitwareMedical/ITKMinimalPathExtraction ?

**Comment by aylward** [comment]
This was done to address a build error against prior versions of Slicer.
Please don't revert.

s

On Wed, Jan 13, 2016 at 4:32 PM, Jean-Christophe Fillion-Robin <
notifications@github.com> wrote:

> @thewtex <https://github.com/thewtex> Should Pr be done on
> InsightSoftwareConsortium/ITKMinimalPathExtraction instead of
> KitwareMedical/ITKMinimalPathExtraction ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/ITKMinimalPathExtraction/pull/4#issuecomment-171441202>
> .
>



-- 
====================================================
Stephen R. Aylward, Ph.D.
Senior Director of Operations, North Carolina, Kitware, Inc.
http://www.kitware.com and http://www.aylward.org
(919) 969-6990 x300
====================================================

**Comment by thewtex** [comment]
@jcfr Yes, thanks for making the PR on InsightSoftwareConsortium/ITKMinimalPathExtraction, too.

@aylward @jcfr has not reverted the prior change but has just moved it to a named branch for clarity. The named branch also includes @sumedhasingla 's fix, which addresses the TubeTK build on Windows :-).

  https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/compare/master...KitwareMedical:support-itk-older-v4.9rc01-2015-10-25-611676c

The sha in TubeTK master:

  https://github.com/KitwareMedical/TubeTK/blob/fdaf1243c858bfd70dcf669d8e2268e43397070c/CMake/Superbuild/ExternalProjectsConfig.cmake#L54

is still present in the repository:

  https://github.com/KitwareMedical/ITKMinimalPathExtraction/commit/51b1c2c97e9f12fb38039e8546612c452b512695

**Pull request merged**
